Howso:
  client: howso.community.client.HowsoEngineClient
  client_extra_params:
     debug: True
     check_version: False
     amalgam:
        embedded: howso.community.lib.amlg
        library_postfix: -mt
        trace: True
        execution_trace_dir: ./traces/
     core:
        embedded: howso.community.lib.core
