name: Reusable WF - Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      payload:
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:

  test-3-8:
    if: inputs.payload != ''
    uses: "./.github/workflows/pytest.yml"
    secrets: inherit
    with:
      python-version: "3.8"
      payload: "${{ inputs.payload }}"

  test-3-11:
    if: inputs.payload != ''
    uses: "./.github/workflows/pytest.yml"
    secrets: inherit
    with:
      python-version: "3.11"
      payload: "${{ inputs.payload }}"