name: Reusable WF - Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:

  build-test-package:
    uses: "./.github/workflows/build.yml"
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      build-type: 'release'
